### ISSUE TITLE
Provide default strings for all types of default formats

### ISSUE THREAD

**Issue by jurmous** [Tzinov15/SwaggerBank#11]
Problem with Random generation: 
```
Error: ERROR: No value found for GenerationOptions[date]
```
Default data types.
http://swagger.io/specification/#data-types-12

**Comment by Tzinov15** [comment]
See https://github.com/Tzinov15/SwaggerBank/pull/14/files, I believe I have added all of the default string format types that are in that Swagger link both as static properties in the `config/options.js` and as random properties that can be generated. Let me know and then I'll close this

**Comment by jurmous** [comment]
It looks complete so for me it can be closed. Thanks 😄
